baseurl = "http://timclifford.io/"
languageCode = "en-us"
title = "timclifford.io"
theme = "hugo-steam-theme"
disqusShortname = "timothyclifford"
paginate = 10

[params]

	title = "Tim Clifford"
	subtitle = "Adventures in NULL REFERENCE EXCEPTION"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Tim Clifford"
	bio = "Australian software developer"
	description = ""
	location = "Currently in Shanghai, China"
	twitter = "timothyclifford"
	github = "timothyclifford"

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	comments = ""

	# Customize or translate the strings
	keepReadingStr = "More"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
